### ISSUE TITLE
Unregister from bower.io

### ISSUE THREAD

**Issue by tocker** [jbcpollak/cloudinary_angular#15]
Hi @jbcpollak,

We appreciate the attention!
However since this repository is deprecated, could you please [unregister](http://bower.io/docs/creating-packages/#unregister) it from bower?
Some of our users found having two libraries confusing.

Thanks!
@tocker from @cloudinary

**Comment by jbcpollak** [comment]
@tocker - This is a good idea, I had forgotten I registered the project with Bower. I have no problem unregistering it, but I'm concerned about what it will do to downstream projects that might already depend on this project.

I don't see any convenient way to alert uses that the package will be removed and it has been marked as deprecated for a long while, so I've gone ahead and unregistered.
